[2023-09-19 19:03:04,214], [ERROR], [Internal Server Error: /api-request/], [C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django\utils\log.py], [(<class 'TypeError'>, TypeError("'Meta.fields' must not contain non-model field names: user"), <traceback object at 0x0000021E9410FEC0>)]
Traceback (most recent call last):
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 68, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 20, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django_filters\rest_framework\backends.py", line 51, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django_filters\filterset.py", line 62, in __new__
    new_class.base_filters = new_class.get_filters()
  File "C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django_filters\filterset.py", line 349, in get_filters
    raise TypeError(
TypeError: 'Meta.fields' must not contain non-model field names: user
[2023-09-19 19:03:04,230], [ERROR], ["GET /api-request/ HTTP/1.1" 500 132486], [C:\Users\root\Desktop\MVP\skidki\venv\lib\site-packages\django\core\servers\basehttp.py], [None]
